# configs/trainer/autoencoder.yaml

max_epochs: 200
batch_size: 4          
save_plots: true       

optimiser:
  _target_: torch.optim.Adam    
  lr: 1e-3                                 

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 3
  min_lr: 1e-6

early_stopping:
  _target_: big_brain.training.stopping.EarlyStopper
  mode: min
  patience: 6
  delta: 1e-4