# configs/checkpoint/on_auroc.yaml

_target_: pytorch_lightning.callbacks.ModelCheckpoint
dirpath: ${hydra:runtime.output_dir}/checkpoints
filename: epoch{epoch:03d}-auroc{val_auroc:.4f}
monitor: val_auroc
mode: max
save_top_k: 3
every_n_epochs: 1
auto_insert_metric_name: false