# configs/checkpoint/on_f1.yaml

_target_: pytorch_lightning.callbacks.ModelCheckpoint
dirpath: ${hydra:runtime.output_dir}/checkpoints
filename: epoch{epoch:03d}-f1{val_f1:.4f}
monitor: val_f1
mode: max
save_top_k: 3
every_n_epochs: 1
auto_insert_metric_name: false