# configs/callbacks/checkpoint.yaml

_target_: pytorch_lightning.callbacks.ModelCheckpoint
dirpath: ${hydra:runtime.output_dir}
filename: model
monitor: val_loss
mode: min
save_top_k: 1
every_n_epochs: 1
auto_insert_metric_name: false