# configs/checkpoint/on_f1.yaml

_target_: pytorch_lightning.callbacks.ModelCheckpoint
dirpath: ${hydra:runtime.output_dir}/checkpoints
filename: epoch{epoch:03d}-mae{val_mae:.4f}
monitor: val_mae
mode: min
save_top_k: 3
every_n_epochs: 1
auto_insert_metric_name: false