# configs/model/custom_ae_exact_shape.yaml

_target_: big_brain.models.autoencoder.ConvAutoEncoder

latent_dim: 512

encoder_cfg:
  - _target_: big_brain.models.blocks.ConvBlock3D
    in_ch: 1
    out_ch: 32

  - _target_: big_brain.models.blocks.ConvBlock3D
    in_ch: 32
    out_ch: 64

  - _target_: big_brain.models.blocks.ConvBlock3D
    in_ch: 64
    out_ch: 128

  - _target_: big_brain.models.blocks.ConvBlock3D
    in_ch: 128
    out_ch: 128

  - _target_: big_brain.models.blocks.ConvBlock3D
    in_ch: 128
    out_ch: 256

decoder_cfg:
  - _target_: big_brain.models.blocks.DeconvBlock3D
    in_ch: 256
    out_ch: 128

  - _target_: big_brain.models.blocks.DeconvBlock3D
    in_ch: 128
    out_ch: 64

  - _target_: big_brain.models.blocks.DeconvBlock3D
    in_ch: 64
    out_ch: 32

  - _target_: big_brain.models.blocks.DeconvBlock3D
    in_ch: 32
    out_ch: 1

