# configs/config.yaml

seed: 42
test: false

defaults:
  - _self_
  - datamodule: transformer
  - model: transformer
  - trainer: default
  - logger: tensorboard
  - early_stopping: on_loss
  - checkpoint: on_loss