# configs/config.yaml

seed: 42
max_epochs: 200

defaults:
  - _self_
  - model: autoencoder
  - loss: mse
  - datamodule: autoencoder
  - optimiser: adamw
  - scheduler: warmup_cosine
  - stopper: early

