# configs/config.yaml

seed: 42
test: false
task: age

defaults:
  - _self_
  - datamodule: finetuner
  - model: regression_head
  - trainer: default
  - logger: tensorboard
  - early_stopping: on_mae
  - checkpoint: on_mae