# configs/config.yaml

seed: 42
test: false
task: tri_cdr

defaults:
  - _self_
  - datamodule: finetuner
  - model: multiclass_head
  - trainer: default
  - logger: tensorboard
  - early_stopping: on_auroc
  - checkpoint: on_auroc