# configs/config.yaml

seed: 69
test: true
task: gender

defaults:
  - _self_
  - datamodule: finetuner
  - model: binary_head
  - trainer: default
  - logger: tensorboard
  - early_stopping: on_auroc
  - checkpoint: on_auroc