# configs/config.yaml

seed: 69
test: true
task: handedness

defaults:
  - _self_
  - datamodule: autoencoder
  - model: autoencoder
  - trainer: default
  - logger: tensorboard
  - early_stopping: on_ssim
  - checkpoint: on_ssim