# configs/datamodule/autoencoder.yaml

_target_: big_brain.data.datamodules.AEDataModule
data_dir: /home/spieterman/dev/big-brain-model/data/autoencoder
batch_size: 6
val_split: 0.05
test_split: 0.05
num_workers: 12
pin_memory: true
use_sampler: true
alpha: 0.3
sample_fraction: 0.0
enable_aug: false
seed: ${seed}