# configs/early_stopping/on_loss.yaml

_target_: pytorch_lightning.callbacks.EarlyStopping

monitor: val_f1        # metric logged with self.log(...) in def validation_step()
mode: max              # "min" for loss, "max" for accuracy
patience: 8            # stop after 5 “no-improvement” epochs
min_delta: 0.001      # minimum change to qualify as an improvement
verbose: true          # set true for console messages